# Generated by Django 4.2 on 2023-04-15 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_rename_user_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('addres', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('lot_link', models.TextField()),
                ('download_link', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
